<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240212183141 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Symfony 7 update, with new entities n so on.';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE footer_link (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, url VARCHAR(255) NOT NULL, title VARCHAR(255) NOT NULL, priority SMALLINT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE link_block (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE sub_link_block (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, url VARCHAR(255) NOT NULL, title VARCHAR(255) NOT NULL, link_block_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_6B58312447E2C5 ON sub_link_block (link_block_id)');
        $this->addSql('ALTER TABLE sub_link_block ADD CONSTRAINT FK_6B58312447E2C5 FOREIGN KEY (link_block_id) REFERENCES link_block (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE mascot_group ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE mascot_group ALTER directories TYPE JSON USING (directories::JSON)');
        $this->addSql('COMMENT ON COLUMN mascot_group.directories IS \'\'');
        $this->addSql('ALTER TABLE rss__group ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE rss__result ADD created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE rss__result ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE rss__result ALTER seen_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN rss__result.seen_at IS \'\'');
        $this->addSql('ALTER TABLE rss__search ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE sub_link_block DROP CONSTRAINT FK_6B58312447E2C5');
        $this->addSql('DROP TABLE footer_link');
        $this->addSql('DROP TABLE link_block');
        $this->addSql('DROP TABLE sub_link_block');
        $this->addSql('ALTER TABLE mascot_group ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE mascot_group ALTER directories TYPE TEXT');
        $this->addSql('COMMENT ON COLUMN mascot_group.directories IS \'(DC2Type:array)\'');
        $this->addSql('ALTER TABLE rss__group ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE rss__search ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE rss__result DROP created_at');
        $this->addSql('ALTER TABLE rss__result ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE rss__result ALTER seen_at TYPE DATE');
        $this->addSql('COMMENT ON COLUMN rss__result.seen_at IS \'(DC2Type:date_immutable)\'');
    }
}
